disabled_rules: # rule identifiers to exclude from running
  - line_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - type_body_length
opt_in_rules: # some rules are only opt-in

included: # paths to include during linting. `--path` is ignored if present.

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
